### ISSUE TITLE
Support for ebs_optimized instances

### ISSUE THREAD

**Issue by andrassy** [cookpad/terraform-aws-eks#142]
For some disk / network intensive workloads it's desirable to use `ebs_optimized` instances to allocate additional dedicated bandwidth for EBS traffic.

**Comment by errm** [comment]
I am fairly sure that all of the modern instance types that support EBS optimisation have it enabled by default see: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html

You shouldn't have to do anything apart from setting `instance_types` to (a) suitable type(s).

The documentation includes an example here https://github.com/cookpad/terraform-aws-eks/tree/master/modules/asg_node_group#instance_family--instance_types

Am I missing anything here?

**Comment by andrassy** [comment]
I wasn't aware of the auto-enable / override on some (most) instance types. From the instance details in the AWS Console it certainly looks like the `ebs_optimized` flag is explicitly set to `false` - a bit odd that this generally but not always means `true` depending on the instance type! 🤕 

Thanks for your advice / knowledge! 🙇‍♂️
