### ISSUE TITLE
`NodeClockNotSynchronising` alert constantly fires since deploying bottlerocket nodes!

### ISSUE THREAD

**Issue by errm** [cookpad/terraform-aws-eks#157]
🔗 https://github.com/bottlerocket-os/bottlerocket/issues/1183

**Comment by errm** [comment]
I have pushed a PR for this issue upstream https://github.com/bottlerocket-os/bottlerocket/pull/1184

**Comment by gregdek** [comment]
PR was merged; have you been able to test if this resolved the issue?

**Comment by errm** [comment]
I tested the changes manually... but I haven't yet built an image myself.

I am not sure I have time to work on this next week, so we might just wait for the next release...

**Comment by errm** [comment]
I have verified this is fixed now!
