### ISSUE TITLE
Use regional endpoints for sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by takanabe** [cookpad/terraform-aws-eks#160]
## Background

We can use Regional AWS STS endpoints instead of the global endpoint to reduce latency, build in redundancy, and increase session token validity when pods execute `sts:AssumeRoleWithWebIdentity` for IRSA. However, K8s manifests don't have `AWS_STS_REGIONAL_ENDPOINTS=regional` to use the regional endpoints. So, I will add the environment variable to the manifests.

## Target

```
> ag -l eks.amazonaws.com/role-arn
modules/cluster/addons/aws-ebs-csi-driver.yaml
modules/cluster/addons/cluster-autoscaler.yaml
modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/eks_iam_for_sa.yaml
modules/cluster/addons/kustomize/overlays/aws-alb-ingress-controller/eks_iam_for_sa.yaml
modules/cluster/addons/helm/cluster-autoscaler.yaml
modules/cluster/addons/aws-alb-ingress-controller.yaml
```

## Related info

* [Managing AWS STS in an AWS Region](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html)

**Comment by errm** [comment]
Seems like a good optimisation
