### ISSUE TITLE
Managed node groups

### ISSUE THREAD

**Issue by errm** [cookpad/terraform-aws-eks#164]
Managed node groups now support custom launch templates... but not (yet) spot instances.

We could consider adding support for them to the module... as they might be useful if spot instances are not required.

I don't think it's a priority though!

**Comment by dan-slinky-ckpd** [comment]
🎉 https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-provisioning-and-managing-ec2-spot-instances-in-managed-node-groups/
