### ISSUE TITLE
Allow users to pass their own container registry as a variable

### ISSUE THREAD

**Issue by ettiee** [cookpad/terraform-aws-eks#171]
Allowing them to avoid docker rate limits if desired

**Comment by ettiee** [comment]
Is a current bug, but if the upstream projects have the images hosted elsewhere (not dockerhub) we could just update those instead

**Comment by ettiee** [comment]
For the 1.18 release we will remove any remaining dependency on dockerhub (e.g. #191 ) but won't include this feature.
But we'll keep this issue open so we can add it later

**Comment by errm** [comment]
All add-ons installed by the module use public eks images managed by aws now!
