### ISSUE TITLE
Add cert-manager and set UseCertManager=true in aws-load-balacner-controller

### ISSUE THREAD

**Issue by ettiee** [cookpad/terraform-aws-eks#205]
Because of the way we template helm charts and commit them, we've got the webhook certs being generated every time you run `hack/generate_addons.sh` which is kinda icky (see https://github.com/cookpad/terraform-aws-eks/pull/204#discussion_r598689545)

@aidy and I discussed it - we're going to:

- Add cert-manager to critical addons (deploy if load-balancer-controller is being deployed)
- Set `enableCertManager: true` in [aws-load-balancer-controller values file](https://github.com/cookpad/terraform-aws-eks/blob/master/modules/cluster/addons/helm/aws-load-balancer-controller.yaml)

**Comment by aidy** [comment]
I think we give cert-manager a selfSigned issuer for this: https://cert-manager.io/docs/configuration/selfsigned/

**Comment by ettiee** [comment]
Here's the recommended cert-manager deployment from aws-load-balancer-controller https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/#install-cert-manager
And the helm chart https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm

**Comment by ettiee** [comment]
@dan-slinky-ckpd good for have your 👀  on this as the Q2 release manager. The current process for including a helm chart (template, commit manifests, apply in module) meant we generate a self-signed cert which gets committed to the repo. We've recommended this approach to solve
- implication that we might have conflicts with fargate node groups according to the aws-load-balancer-controller documentation
- Alternatives considered - change the process by which we apply helm charts

**Comment by ettiee** [comment]
Superseded by #224
