### ISSUE TITLE
 Error: local-exec provisioner error

### ISSUE THREAD

**Issue by nichecloudexpert** [cookpad/terraform-aws-eks#223]
Error: local-exec provisioner error
│
│   with module.cluster.aws_eks_cluster.control_plane,
│   on ..\..\modules\cluster\main.tf line 38, in resource "aws_eks_cluster" "control_plane":
│   38:   provisioner "local-exec" {
│
│ Error running command 'curl --output /dev/null --insecure --silent https://4015B88453E193304E8384535B533173.gr7.us-east-1.eks.amazonaws.com/healthz;': exit status

**Comment by errm** [comment]
Hi could you share some more info?

What output do you see when you run this command manually... e.g:

```
curl -v --insecure https://4015B88453E193304E8384535B533173.gr7.us-east-1.eks.amazonaws.com/healthz
```

A common reason for this is that where you are running terraform doesn't have access to the eks cluster endpoint. If you are running terraform inside your private network then you need to have the security groups setup to allow API requests on port 443, if you are running terraform outside of your VPC then you need to ensure `endpoint_public_access` is `true` (it defaults to that).
