### ISSUE TITLE
Reconsider addons in cluster module

### ISSUE THREAD

**Issue by ettiee** [cookpad/terraform-aws-eks#224]
We want to improve the experience of the cluster addons:

- Users may want to configure addons for their own use-case not use our opinionated 
- helm templating then committing the templated manifests is a manual process, can lead to huge yaml files
- Users might want to upgrade the addons on their own schedule rather than use the version we pin to our EKS release
- [kubectl](https://github.com/cookpad/terraform-aws-eks/tree/master/modules/cluster/kubectl) can have token timeouts against the kubernetes api 

Possible approach after discussion with @errm:

- Remove non-critical addons from the module (discuss with teams and agree addons to remove)
- Use [AWS EKS addons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) for critical addons where supported
- Create kustomize bases for addons we want to keep and manage with [kustomize provider](https://registry.terraform.io/providers/kbst/kustomize/latest/docs)

The expectation after this change is that users will manage addons themselves or consume some other packaging format

**Comment by mtpereira** [comment]
:memo: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon

**Comment by aidy** [comment]
Revisit support for new add-ons, and swap out where applicable.

**Comment by aidy** [comment]
Looks like there's now a [EBS CSI eks addon](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html).

Other than that, we should revisit kube-proxy.

**Comment by aidy** [comment]
> Looks like there's now a EBS CSI eks addon.

Actually, that's still a preview build, so let's hold off on that one for this.

```
        {
            "addonName": "aws-ebs-csi-driver",
            "type": "storage",
            "addonVersions": [
                {
                    "addonVersion": "v1.4.0-eksbuild.preview",
                    "architecture": [
                        "amd64"
                    ],
                    "compatibilities": [
                        {
                            "clusterVersion": "1.21",
                            "platformVersions": [
                                "eks.3+"
                            ],
                            "defaultVersion": true
                        }
                    ]
                }
            ]
        }

```

**Comment by aidy** [comment]
Ah, looks like there's still an issue with kube-proxy in 1.21: https://github.com/aws/containers-roadmap/issues/657#issuecomment-966347660

**Comment by aidy** [comment]
So there's no more we can do here for 1.21

**Comment by aidy** [comment]
`aws eks describe-addon-versions --kubernetes-version 1.21`

ebs csi has moved to a not-preview version, but I think it's missed the cut for this.

We'll look at it for 1.22
