### ISSUE TITLE
ingress not working

### ISSUE THREAD

**Issue by fahimghl** [cookpad/terraform-aws-eks#243]
No endpoints could be generated from ingress. ALB ingress controller removed from 1.19.0?

**Comment by errm** [comment]
Hi there...  We have been working on removing some of the non-core parts of this module.  We want to focus on provisioning the base eks cluster in this module, and leave some other decisions about which addons you wish to use to users.

See: https://github.com/cookpad/terraform-aws-eks/issues/224

To this end we intentionally removed the ingress controller stuff from the 1.19 release.

If you want an ingress controller that uses ALB aws-load-ballancer-controller is the current recommended thing.  They suggest using helm to deploy to your cluster see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/

**Comment by aidy** [comment]
Hopefully @errm's answer provided all the information necessary.

No further comments - I'm closing this.
