### ISSUE TITLE
Quieten drift detection in plans for desired_capacity attribute of ASGs under terraform 0.15.0 and higher

### ISSUE THREAD

**Issue by andrassy** [cookpad/terraform-aws-eks#266]
In Terraform 1.x.x, plans produce a [drift detection section in the output](https://github.com/cookpad/global-aws/pull/762#issuecomment-962961595). We know that `desired_state` is going to drift between applies, so we should explicitly ignore it to keep logs quiet / make it easier to spot "real" drift.

Update 2021-11-16: Proposal was to add `ignore_changes` lifecycle meta-attribute on `desired_capacity` for ASGs but it seems this will not have the desired effect. See [below](https://github.com/cookpad/terraform-aws-eks/issues/266#issuecomment-970124193)

**Comment by andrassy** [comment]
Hello @cookpad/platform-services-team. As it's kind of trivial I have a branch with this minor change on it, but I don't have permission to push it. How would you like me to proceed? 🙏

**Comment by andrassy** [comment]
https://github.com/hashicorp/terraform/issues/28803#issuecomment-951209299 - turns out this might not have the desired effect after all 😭. Thanks @samjacobclift for finding this discussion thread.

Maybe we should close this issue for now?

**Comment by samjacobclift** [comment]
I think so 😢

**Comment by andrassy** [comment]
I've updated the ticket to the requirement still makes sense without specifying a solution that won't work.

**Comment by ettiee** [comment]
Thanks for raising @andrassy - I've read through the discussion thread on https://github.com/hashicorp/terraform/issues/28803 and I agree we should wait until a next step proposal comes out from the terraform maintainers.

**Comment by errm** [comment]
IMO I think we should close this issue.  This issue is an upstream issue with terraform - there may be a solution (someday) in the future, but I would like the open issues here to reflect work that we could pick up and complete today (given enough effort).
