### ISSUE TITLE
Add gpu support for bottlerocket 

### ISSUE THREAD

**Issue by ettiee** [cookpad/terraform-aws-eks#295]
This is enabled in 1.21 by the [aws-k8s-1.21-nvidia variant from bottlerocket](https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-EKS.md#aws-k8s--nvidia-variants). 

📝  make sure you update the docs if working on this issue https://github.com/cookpad/terraform-aws-eks/blob/25ca1db1397441e408b355db7b312dd2ce107af0/modules/asg_node_group/README.md#bottlerocket

NB: [the device plugin is pre-baked into the AMI](https://github.com/weaveworks/eksctl/issues/4760) so users won't need to manage the nvidia plugin daemonset, and we can remove from cluster addons when using bottlerocket.

**Comment by aidy** [comment]
closed with #298
