### ISSUE TITLE
Nginx Ingress controller

### ISSUE THREAD

**Issue by dan-slinky-ckpd** [cookpad/terraform-aws-eks#90]
In the same vein to https://github.com/cookpad/terraform-aws-eks/issues/87 can you see value in adding the Nginx Ingress controller to the module? 

There are going to be situations where we might want to use the Nginx Ingress controller with an NLB rather than AWS+ALB, for example a service we want to place behind a Basic Auth implementation.

**Comment by errm** [comment]
I think if we want / need to run many different ingress implementations it's probably an argument to keep their provisioning out of this module!

Having said that for basic auth, and other general ngnix glue we would usually just use the front container pattern...

**Comment by errm** [comment]
We will not include Nginx Ingress controller in this module. aws-alb-ingress-controller will be the default solution... if you want something else you need to manage it by yourself!
